name: Build package

on:
  push:
    branches:
      - master

jobs:
  linux-amd64-build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Checkout blst
        run: |
          git clone https://github.com/supranational/blst.git
          cd blst
          git checkout v0.3.10

      - name: Build blst
        run: |
          cd blst/bindings/java
          ./run.me

      - name: Upload blst src and bin
        uses: actions/upload-artifact@v3
        with:
          name: blst-linux-amd64
          path: |
            blst/bindings/java/supranational/blst/Linux/
            blst/bindings/java/supranational/blst/*.java

  macos-build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Checkout blst
        run: |
          git clone https://github.com/supranational/blst.git
          cd blst
          git checkout v0.3.10

      - name: Build blst
        run: |
          cd blst/bindings/java
          export CC="cc"
          export CXX="c++ -std=c++11"
          ./run.me

      - name: Upload blst src and bin
        uses: actions/upload-artifact@v3
        with:
          name: blst-macos-amd64
          path: |
            blst/bindings/java/supranational/blst/Mac/
            blst/bindings/java/supranational/blst/*.java
