name: Build package

on:
  push:
    branches:
      - master

jobs:
  linux-amd64-build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install swig

      - name: Checkout blst
        run: |
          git clone https://github.com/supranational/blst.git
          cd blst
          git checkout v0.3.10

      - name: Build blst
        run: |
          cd blst/bindings/java
          ./run.me

      - name: Update blst jar
        uses: actions/upload-artifact@v3
        with:
          name: blst-linux-amd64
          path: blst/bindings/java/supranational.blst.jar
